title: ""
email: 
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ivanruski

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections_dir: collections

collections:
  essays: 
    label: "essays"
    display_name: "Essays"
    output: true
  podcast_notes:
    label: "podcast_notes"
    display_name: "Podcast notes"
    output: true
  posts:
    output: true


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
